# Generated by Django 2.2.18 on 2025-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20250225_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportnote',
            name='content',
            field=models.TextField(blank=True, help_text='Escribe el contenido de la nota', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='reportnote',
            name='heading',
            field=models.TextField(help_text='Añade un título para esta nota', verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='include_signature',
            field=models.BooleanField(default=True, help_text='¿Quieres firma al final del PDF?', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='report_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=8, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='report_type',
            field=models.CharField(max_length=128, verbose_name='Tipo de informe'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Selecciona los grupos que pueden ver este informe. Dejar en blanco para mantenerlo privado.', to='auth.Group', verbose_name='Visible para'),
        ),
    ]
