# Generated by Django 2.2.18 on 2025-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0019_auto_20210323_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['number'], 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
        migrations.AlterModelOptions(
            name='unittype',
            options={'ordering': ('vendor__name', 'model'), 'verbose_name': 'unit type', 'verbose_name_plural': 'unit types'},
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='Nombre de la instalación', max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(help_text='Identificador de la instalación radiactiva', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(blank=True, help_text='Name for this unit type', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='unitavailabletime',
            unique_together={('unit', 'date_changed')},
        ),
        migrations.AlterUniqueTogether(
            name='unitavailabletimeedit',
            unique_together={('unit', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='unittype',
            unique_together={('model', 'vendor', 'unit_class')},
        ),
    ]
