# Generated by Django 2.2.18 on 2025-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0020_auto_20250225_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='notes',
        ),
        migrations.AddField(
            model_name='unit',
            name='tube_sn',
            field=models.CharField(blank=True, help_text='Tube Serial Number', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Equipment Serial Number', max_length=256, null=True),
        ),
    ]
