# Generated by Django 2.2.18 on 2025-03-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0021_auto_20250227_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='tube_sn',
            new_name='tube_serial_number',
        ),
    ]
