# Generated by Django 2.2.18 on 2025-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0022_auto_20250305_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='system_number',
            field=models.CharField(blank=True, help_text='Only for GE Healthcare machines, if we already have a Serial Number registered.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='active',
            field=models.BooleanField(default=True, help_text='Set to false if unit is no longer in use.'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='date_acceptance',
            field=models.DateField(help_text='Changing acceptance date will delete unit available times that occur before it.', verbose_name='Acceptance date'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='install_date',
            field=models.DateField(blank=True, help_text='Optional install date.', null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_serviceable',
            field=models.BooleanField(default=True, help_text='Set to true to enable this unit to be selectable in service events.'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='location',
            field=models.CharField(blank=True, help_text='Optional location information.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(help_text='The display name for this unit.', max_length=256),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='A unique number for this unit. Leave blank to have it assigned automatically.', unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='serial_number',
            field=models.CharField(help_text='Equipment Serial Number. For GE Healthcare machines, use System Number instead if there is no serial number registered.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tube_serial_number',
            field=models.CharField(help_text='Tube Serial Number.', max_length=256, null=True),
        ),
    ]
