# Generated by Django 2.2.18 on 2025-03-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0023_auto_20250306_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='units.Site'),
        ),
    ]
