# Generated by Django 2.2.18 on 2025-02-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0026_auto_20210126_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouplinkerinstance',
            unique_together=set(),
        ),
    ]
