# Generated by Django 2.2.18 on 2025-05-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0027_auto_20250225_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ('name',), 'verbose_name': 'service area', 'verbose_name_plural': 'service areas'},
        ),
    ]
