# Generated by Django 2.2.18 on 2025-05-16 11:55

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0028_auto_20250516_1133'), # Or the latest migration
        # Potentially add ('units', 'XXXX_some_units_migration') if UnitServiceArea depends on it
    ]

    operations = [
        # This is a simplified AddField; ensure all attributes match your model
        # It's often better to use RunSQL for such corrective actions if the column is truly missing
        # despite a previous migration claiming to add/alter it.
        # migrations.AddField(
        #     model_name='serviceevent',
        #     name='unit_service_area',
        #     field=models.ForeignKey(
        #         on_delete=django.db.models.deletion.PROTECT,
        #         to='service_log.UnitServiceArea',
        #         verbose_name='unit service area',
        #         # Add null=True, blank=True if appropriate and matching the original intent
        #         # This is tricky because AlterField in 0025 might have assumed a default
        #         # or handled nullability.
        #         # For a missing column, you'd need to decide its nullability.
        #         # If the original model field allows null, then null=True here.
        #     ),
        # ),
        # Safer: Use RunSQL to add if missing
        migrations.RunSQL(
            sql="""
            IF COL_LENGTH('dbo.service_log_serviceevent', 'unit_service_area_id') IS NULL
            BEGIN
                ALTER TABLE dbo.service_log_serviceevent
                ADD unit_service_area_id INT NULL; -- Adjust NULL/NOT NULL based on model
            END;
            """,
            reverse_sql="""
            IF COL_LENGTH('dbo.service_log_serviceevent', 'unit_service_area_id') IS NOT NULL
            BEGIN
                -- Consider implications before dropping a column, especially if FKs exist
                -- ALTER TABLE dbo.service_log_serviceevent DROP COLUMN unit_service_area_id;
            END;
            """
        ),
    ]
