# Generated by Django 2.2.18 on 2025-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0058_testlistinstance_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlist',
            name='warning_message',
            field=models.CharField(blank=True, default='NO APTO', help_text='Message given when a test value is out of tolerance.  Leave blank to disable warnings from being shown when tests are out of tolerance.', max_length=255),
        ),
    ]
