# Generated by Django 2.2.18 on 2025-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0059_auto_20250225_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreviewrule',
            name='pass_fail',
            field=models.CharField(choices=[('not_done', 'No realizada'), ('ok', 'OK'), ('tolerance', 'Tolerance'), ('action', 'Action'), ('no_tol', 'No Tol Set')], help_text='Pass fail state of test instances to apply this rule to.', max_length=15),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='pass_fail',
            field=models.CharField(choices=[('not_done', 'No realizada'), ('ok', 'OK'), ('tolerance', 'Tolerance'), ('action', 'Action'), ('no_tol', 'No Tol Set')], db_index=True, editable=False, max_length=20),
        ),
    ]
