# Generated by Django 2.2.18 on 2025-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0060_auto_20250411_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='skipped',
            field=models.BooleanField(default=False, help_text='Clica si por algún motivo no se realizó la prueba (puedes añadir un comentario)'),
        ),
    ]
