# Generated by Django 2.2.18 on 2025-05-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0061_auto_20250422_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='comment',
            field=models.TextField(blank=True, help_text='Añade un comentario sobre esta prueba', null=True),
        ),
    ]
